; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; lib_extra_dirs = C:\Users\Simon\OneDrive\Dateien\Business\Hühnerklappe\Software\Uhr\Test_DeepSleep\arduino-esp32\arduino-esp32-master\tools\sdk\include\driver\driver

build_flags = -D MENU_DEBUG
lib_deps = 
	Wire
	fmalpartida/LiquidCrystal@^1.5.0
	adafruit/RTClib@^1.13.0
	neu-rah/ArduinoMenu library@^4.21.3
	faboplatform/FaBo 215 RTC PCF2129@^1.0.0
	mbed-nxp-ip/PCF2127@0.0.0+sha.e2a6ac61fcbd
	hideakitai/PCF2129@^0.1.0
	madhephaestus/ESP32AnalogRead@^0.1.2
	northernwidget/DS3231@^1.0.7
	neu-rah/streamFlow@0.0.0-alpha+sha.bf16ce8926
